# Generated by Django 4.0.4 on 2022-04-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_scope_tags_scope_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.Tags', to='articles.article'),
        ),
    ]
