# Generated by Django 4.0.4 on 2022-04-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_scope_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'ordering': ['tag'], 'verbose_name': 'Промежуточная таблица', 'verbose_name_plural': 'Промежуточные таблицы'},
        ),
    ]
